In [1]:
import nltk
#nltk.download()


In [2]:
#nltk.download("punkit")

In [2]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [3]:
# Tokenizing sentences
sentences = nltk.sent_tokenize(paragraph)




In [4]:
sentences

['I have three visions for India.',
 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.',
 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.',
 'Yet we have not done this to any other nation.',
 'We have not conquered anyone.',
 'We have not grabbed their land, their culture, \n               their history and tried to enforce our way of life on them.',
 'Why?',
 'Because we respect the freedom of others.That is why my \n               first vision is that of freedom.',
 'I believe that India got its first vision of \n               this in 1857, when we started the War of Independence.',
 'It is this freedom that\n               we must protect and nurture and build on.',
 'If we are not free, no one will respect us.',
 'My second vision for India’s developme

In [5]:
# Tokenizing words
words = nltk.word_tokenize(paragraph)


In [6]:
words[0],sentences[0]

('I', 'I have three visions for India.')

In [7]:
len(words)

399

In [8]:
len(sentences)

31

In [9]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [10]:
stemmer=PorterStemmer()

In [11]:
for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]= ' '.join(words)

In [12]:
len(words)

5

In [27]:
words

['I', 'see', 'four', 'mileston', 'career']

In [28]:
len(sentences)

31

In [31]:
sentences

['I three vision india .',
 'In 3000 year histori , peopl world come invad us , captur land , conquer mind .',
 'from alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot us , took .',
 'yet done nation .',
 'We conquer anyon .',
 'We grab land , cultur , histori tri enforc way life .',
 'whi ?',
 'becaus respect freedom others.that first vision freedom .',
 'I believ india got first vision 1857 , start war independ .',
 'It freedom must protect nurtur build .',
 'If free , one respect us .',
 'My second vision india ’ develop .',
 'for fifti year develop nation .',
 'It time see develop nation .',
 'We among top 5 nation world term gdp .',
 'We 10 percent growth rate area .',
 'our poverti level fall .',
 'our achiev global recognis today .',
 'yet lack self-confid see develop nation , self-reli self-assur .',
 'isn ’ incorrect ?',
 'I third vision .',
 'india must stand world .',
 'becaus I believ unless india stand world , one respect us .',
 'onl

In [32]:
import pandas as pd
sent=pd.DataFrame(sentences)

In [33]:
sent.head()

0
0                             I three vision india .
1  In 3000 year histori , peopl world come invad ...
2  from alexand onward , greek , turk , mogul , p...
3                                  yet done nation .
4                                 We conquer anyon .

In [36]:
print(sent.iloc[0:1,0])

0    I three vision india .
Name: 0, dtype: object


# laminizer

In [38]:
from nltk.stem import WordNetLemmatizer

In [40]:
lemmatizer=WordNetLemmatizer()
words = nltk.word_tokenize(paragraph)
sentences = nltk.sent_tokenize(paragraph)

In [41]:
for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]= ' '.join(words)

In [42]:
sentences

['I three vision India .',
 'In 3000 year history , people world come invaded u , captured land , conquered mind .',
 'From Alexander onwards , Greeks , Turks , Moguls , Portuguese , British , French , Dutch , came looted u , took .',
 'Yet done nation .',
 'We conquered anyone .',
 'We grabbed land , culture , history tried enforce way life .',
 'Why ?',
 'Because respect freedom others.That first vision freedom .',
 'I believe India got first vision 1857 , started War Independence .',
 'It freedom must protect nurture build .',
 'If free , one respect u .',
 'My second vision India ’ development .',
 'For fifty year developing nation .',
 'It time see developed nation .',
 'We among top 5 nation world term GDP .',
 'We 10 percent growth rate area .',
 'Our poverty level falling .',
 'Our achievement globally recognised today .',
 'Yet lack self-confidence see developed nation , self-reliant self-assured .',
 'Isn ’ incorrect ?',
 'I third vision .',
 'India must stand world .',
 'Bec

In [43]:
sent_lam=pd.DataFrame(sentences)

In [44]:
sent_lam.head()

0
0                             I three vision India .
1  In 3000 year history , people world come invad...
2  From Alexander onwards , Greeks , Turks , Mogu...
3                                  Yet done nation .
4                              We conquered anyone .

# Bag of word

In [47]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [48]:
ps=PorterStemmer()
wordnet=WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus=[]

In [50]:
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]', ' ', sentences[i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if word not in set(stopwords.words('english'))]
    review= ' '.join(review)
    corpus.append(review)

In [51]:
# creating BOW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 1500)
X=cv.fit_transform(corpus).toarray()

In [52]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [53]:
X=pd.DataFrame(X)

In [54]:
X.shape

(31, 113)

In [55]:
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]', ' ', sentences[i])
    review=review.lower()
    review=review.split()
    review=[wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review= ' '.join(review)
    corpus.append(review)

In [56]:
# creating BOW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 1500)
X=cv.fit_transform(corpus).toarray()

In [57]:
X.shape

(62, 154)

In [58]:
# TD IDF

In [59]:
# creating BOW
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X=cv.fit_transform(corpus).toarray()

In [61]:
X.shape

(62, 154)

In [8]:
import pandas as pd

In [9]:
from nltk.stem import WordNetLemmatizer
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [10]:
corpus=[]

In [11]:
data=pd.read_csv(r'F:\machine learning\NLP\sms spam\SMSSpamCollection', sep='\t', names=["label", "message"])

In [12]:
data.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
data.shape

(5572, 2)

In [14]:
ps=PorterStemmer()
wordnet=WordNetLemmatizer()
#sentences = nltk.sent_tokenize(paragraph)
corpus=[]

In [15]:
for i in range(len(data)):
    review=re.sub('[^a-zA-Z]', ' ', data["message"][i])
    review=review.lower()
    review=review.split()
    review=[wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review= ' '.join(review)
    corpus.append(review)

In [16]:
# creating BOW
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X=cv.fit_transform(corpus).toarray()

In [17]:
X.shape

(5572, 7098)

In [18]:
data["label"].nunique()

2

In [19]:
data["class"]=data["label"].map({"ham":0, "spam":1})

In [20]:
Y=data["class"]

In [21]:
len(Y)

5572

In [22]:
import sklearn
import pandas as pd
#import quandl
import math, datetime
import numpy as np
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from matplotlib import style
import pickle

In [23]:
X=np.array(X)
Y=np.array(Y)

In [24]:
X_train,X_test,Y_train,Y_test= train_test_split( X, Y, test_size=0.3)

In [25]:
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [26]:
clf= make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3) )

In [27]:
clf.fit(X_train, Y_train)

Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('sgdclassifier', SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', ma..._state=None, shuffle=True, tol=0.001,
       validation_fraction=0.1, verbose=0, warm_start=False))])

In [28]:
y_predict=clf.predict(X_train)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [30]:
confusion_matrix(Y_train, y_predict)

array([[3371,    0],
       [  22,  507]], dtype=int64)

In [31]:
accuracy_score(Y_train, y_predict)

0.9943589743589744

In [32]:
y_predict_test=clf.predict(X_test)

In [33]:
confusion_matrix(Y_test, y_predict_test)

array([[1454,    0],
       [ 122,   96]], dtype=int64)

In [34]:
accuracy_score(Y_test, y_predict_test)

0.9270334928229665

In [40]:
from pycaret.classification import *

In [ ]:
exp_clf101 = setup(data = data, target = 'default', session_id=123) 

In [35]:
import lazypredict

In [39]:
from lazypredict.Supervised import LazyClassifier


ImportError: cannot import name '_deprecate_positional_args' from 'sklearn.utils.validation' (C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py)

In [38]:
sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingClassifier

AttributeError: module 'sklearn.ensemble' has no attribute '_hist_gradient_boosting'

In [15]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each